### PR TITLE
Update unofficial.md

### PR DESCRIPTION
**Pull request by Tbkhi**
Adds content.

### CODE REVIEW

**Comment by Tbkhi** [comment]
Bumping that as "not spam".

**Review by glyn — COMMENTED** [review]
Apart from the literal title being incorrect (it should be "Writing down my mental model of unsafe"), I'm really not sure about the credibility of this item. It's a gist and I can't see any references to it when I search (I tried both DDG and Google search engines). If it was recommended numerous people, I might warm to it...

**Comment by Tbkhi** [comment]
It was recommend by the TWIR editing team. I'm unsure about using an archive since it is creative content.

**Comment by glyn** [comment]
> It was recommend by the TWIR editing team. I'm unsure about using an archive since it is creative content.
> 
> https://this-week-in-rust.org/blog/2024/02/21/this-week-in-rust-535/#observationsthoughts

Given the gist is far from a book and is moderately niche in content, I think I'm going to do without it. Thanks for drawing it to my intention. Maybe someone will turn it into proper docs one day.

**Pull request closed without merging**
