### PR TITLE
Update applications.md

### PR DESCRIPTION
**Pull request by kwfn**
Removes a resource duplicated in Applications and Unofficial

### CODE REVIEW

**Review by glyn — COMMENTED** [review]
Hmmm. Please could you tell me which entry this duplicates. E.g. https://esp-rs.github.io/std-training/ is different to https://esp-rs.github.io/book/. Is the one you deleted superseded by the other one?

**Comment by kwfn** [comment]
My mistake I was looking at the descriptions.

**Comment by glyn** [comment]
> My mistake I was looking at the descriptions.

No problem. Would you be interested in becoming a maintainer of this repo in addition to me? You seem keen to keep it up to scratch.

**Comment by glyn** [comment]
Ok, but I could still review your changes, and you could review and merge changes from others. Let me know if you change your mind.

**Pull request closed without merging**
